input_cloud_topic: "/map_nodelet/pointcloud"
step_maybe_topic: "/staircase_detection/steps_centroid"
output_steps_topic: "/staircase_detection/pointcloud/steps"
step_bounding_box_topic: "/staircase_detection/pointcloud/bounding_box"
step_vertical_topic: "/staircase_detection/pointcloud/step_vertical"
robot_pose_topic: "/robotcontrol/odometry"

extract_bool: true
verbose: false
sleep_time: 1.5

#parameters are all in centimeters
voxel_leaf: 0.04
delta_angle: 0.087
z_passthrough: 0.002
distance_threshold: 0.12
cluster_tolerance: 0.1
acceptable_step_height: 0.3
sensor_height_offset: 1.622
sensor_plane_offset: 0.2


