input_cloud_topic: "/mapping_nodelet/pointcloud"
filtered_input_topic: "/mapping_nodelet/filtered"
step_maybe_topic: "/staircase_detection/steps_centroid"
output_steps_topic: "/staircase_detection/staircase"
raw_plane: "/staircase_detection/raw_plane"
step_bounding_box: "/staircase_detection/step_bounding_box"
step_vertical_topic: "/staircase_detection/vertical"
robot_pose_topic: "/robotcontrol/odometry"

extract_bool: true
verbose: true
sleep_time: 1.5

#parameters are all in meters
voxel_leaf: 0.1
delta_angle: 0.087
z_passthrough: 0.002
distance_threshold: 0.03
cluster_tolerance: 0.14
acceptable_step_height: 0.3
sensor_height_offset: 1.622
sensor_plane_offset: 0.2

perception_range: 8.0

step_width: 1.0
step_depth: 0.10
acceptable_step_height: 0.30

