input_cloud: "/mapping_nodelet/pointcloud"
output_steps: "/staricase_detection/steps"
step_bounding_box: "/staricase_detection/bounding_box"
extract_bool: true
delta_angle: 0.087
z_passthrough: 0.002
distance_threshold: 0.12
cluster_tolerance: 0.1

