input_cloud_topic: "/mapping_nodelet/pointcloud"
filtered_input_topic: "/mapping_nodelet/filtered"
step_maybe_topic: "/staircase_detection/steps_centroid"
output_steps_topic: "/staircase_detection/staircase"
raw_plane: "/staircase_detection/raw_plane"
step_bounding_box: "/staircase_detection/step_bounding_box"
step_vertical_topic: "/staircase_detection/vertical"
robot_pose_topic: "/robotcontrol/odometry"

extract_bool: true
verbose: true
sleep_time: 0.0

#parameters are all in meters
voxel_leaf: 0.08
delta_angle: 0.087
z_passthrough: 0.002
distance_threshold: 0.12
normal_distance_threshold: 0.08
cluster_tolerance: 0.12
acceptable_step_height: 0.3
sensor_height_offset: 1.622
sensor_plane_offset: 0.2

perception_range: 6.0

step_width: 2.0
step_depth: 0.35
acceptable_step_height: 0.30


#rotate angle to align cloud to world (in deg)
rotate_angle: -2.0


#museum down
#rotate angle =-2.0
#cluster = 0.12
#distance_threshold: 0.06

#tek14 behind
#rotate_angle: 0.0
#step_depth:0.35
#distance_threshold: 0.12
#cluster_tolerance: 0.12
#normal_distance_threshold: 0.08

#tek14_front
#passthrough for 15cm instead of 10cm
#rotate_angle: -1.0
