input_cloud_topic: "/mapping_nodelet/pointcloud"
filtered_input_topic: "/mapping_nodelet/filtered"
step_maybe_topic: "/staircase_detection/vertical_setup"
output_steps_topic: "/staircase_detection/staircase"
raw_plane: "/staircase_detection/raw_plane"
step_bounding_box: "/staircase_detection/step_bounding_box"
step_vertical_topic: "/staircase_detection/vertical"
robot_pose_topic: "/robotcontrol/odometry"

extract_bool: true
verbose: true
sleep_time: 0.5

#parameters are all in meters
voxel_leaf: 0.08
delta_angle: 0.087
z_passthrough: 0.002
distance_threshold: 0.14
normal_distance_threshold: 0.12
cluster_tolerance: 0.16

sensor_height_offset: 1.622
sensor_plane_offset: 0.2

perception_range: 6.0

step_width: 1.0
step_depth: 0.2
acceptable_step_height: 0.30


#rotate angle to align cloud to world (in deg)
rotate_angle: -2.0

#museum front
#rotate_angle: -2.0
#distance_thre: 0.18
#normal_distnace: 0.1
#cluster_tol: 0.1

#museum down
#rotate angle =-2.0
#cluster_tolerance = 0.12
#distance_threshold: 0.06

#tek14 behind
#rotate_angle: 0.0
#cluster_tolerance: 0.12
#distance_threshold: 0.12
#step_depth:0.35
#normal_distance_threshold: 0.08

#tek14_front
#rotate_angle: -1.0
#distance_threshold: 0.12
#passthrough for 15cm instead of 10cm
#normal_distance_threshold: 0.18

#lappis_3
#rotate_angle: -2.0
#distance_threshold: 0.1
