input_cloud_topic: "/map_nodelet/pointcloud"
step_maybe_topic: "/staircase_detection/steps_centroid"
output_steps_topic: "/staircase_detection/pointcloud/steps"
step_bounding_box_topic: "/staircase_detection/pointcloud/bounding_box"
step_vertical_topic: "/staircase_detection/pointcloud/step_vertical"
robot_pose_topic: "/robotcontrol/odometry/pose/pose/position"
robot_orientation_topic: "/robotcontrol/odometry/pose/pose/orientation"
extract_bool: true
verbose: false

#parameters are all in centimeters
voxel_leaf: 0.04
delta_angle: 0.087
z_passthrough: 0.002
distance_threshold: 0.12
cluster_tolerance: 0.1
acceptable_step_height: 0.3

